# AppVeyor CI build file, https://ci.appveyor.com/project/BarryThePenguin/sparkleshare

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# Don't edit manually! Use `build.bat version` command instead!
shallow_clone: true

pull_requests:
  do_not_increment_build_number: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
# os: Default Azure

platform:
  - x86
  - x64

configuration:
  - Debug

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic MSBuild
before_build:
  - nuget restore HellowWorld.sln

after_build:
  - if %platform%==x86 ( nuget pack HelloWorld.nuspec -version 1.1.2 ) 
  - if %platform%==x64 ( nuget pack HelloWorldx64.nuspec -version 1.1.2 )
  - if %platform%==x86 ( C:\projects\testinstaller\packages\squirrel.windows.1.7.9\tools\Squirrel.exe --releasify HelloWorld.1.1.2.nupkg --no-msi --releaseDir ".\SquirrelReleases\x86" )
  - if %platform%==x64 ( C:\projects\testinstaller\packages\squirrel.windows.1.7.9\tools\Squirrel.exe --releasify HelloWorldx64.1.1.2.nupkg --no-msi --releaseDir ".\SquirrelReleases\x64" )

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: '.\SquirrelReleases\x86\*'
    name: releasesx86

  - path: '.\SquirrelReleases\x64\*'
    name: releasesx64

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 56f7421c2675fa49adf89df2884b3f4ac51f6ce6 # your encrypted token from GitHub
  artifact: /.*\.exe/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only